[build]
  publish = "_site"
  #command = "bash scripts/netlify-build.sh"
  command = "curl -sSOL https://cecil.app/build.sh && bash ./build.sh"

[build.environment]
  #CECIL_CACHE_DIR = "/opt/build/cache/"
  #CECIL_CACHE_ENABLED = "true"
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"

[context.production.environment]
  CECIL_ENV = "production"

[context.deploy-preview.environment]
  CECIL_ENV = "preview"
